// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyextoDAVWebApp.Context;

namespace ProyextoDAVWebApp.Migrations
{
    [DbContext(typeof(LinkliDosDataContext))]
    [Migration("20190524020415_Relacion")]
    partial class Relacion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyextoDAVWebApp.Models.Aplicaciontrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdReclutamientoTrabajo");

                    b.Property<int>("IdUsuario");

                    b.HasKey("Id");

                    b.ToTable("Aplicaciontrabajos");
                });

            modelBuilder.Entity("ProyextoDAVWebApp.Models.EducacionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DondeEstudio");

                    b.Property<DateTime>("FechaFinal");

                    b.Property<DateTime>("FechaInicio");

                    b.Property<int>("IdUsuario");

                    b.HasKey("Id");

                    b.ToTable("EducacionUsuarios");
                });

            modelBuilder.Entity("ProyextoDAVWebApp.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contacto");

                    b.Property<string>("Contrasenia");

                    b.Property<string>("Correo");

                    b.Property<string>("Mision");

                    b.Property<string>("Nombre");

                    b.Property<string>("SobreNosotro");

                    b.Property<string>("Vision");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ProyextoDAVWebApp.Models.NombreTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdReclutamientoTrabajo");

                    b.Property<string>("PuestoTrabajo");

                    b.Property<int?>("ReclutamientoTrabajoId");

                    b.HasKey("Id");

                    b.HasIndex("ReclutamientoTrabajoId");

                    b.ToTable("NombreTrabajos");
                });

            modelBuilder.Entity("ProyextoDAVWebApp.Models.OcupacionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdUsuario");

                    b.Property<string>("Ocupacion");

                    b.HasKey("Id");

                    b.ToTable("OcupacionUsuarios");
                });

            modelBuilder.Entity("ProyextoDAVWebApp.Models.ReclutamientoTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<int?>("EmpresaId");

                    b.Property<int>("IdAplicacionTrabajo");

                    b.Property<int>("IdEmpresa");

                    b.Property<string>("SeRecluta");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ReclutamientoTrabajos");
                });

            modelBuilder.Entity("ProyextoDAVWebApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AplicacionTrabajoIdUsuario");

                    b.Property<string>("Contrasenia")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Correo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Cuidad")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("EducacionUsuarioIdUsuario");

                    b.Property<int?>("OcupacionUsuarioIdUsuario");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("AplicacionTrabajoIdUsuario");

                    b.HasIndex("EducacionUsuarioIdUsuario");

                    b.HasIndex("OcupacionUsuarioIdUsuario");

                    b.ToTable("Usuario","dbo");
                });

            modelBuilder.Entity("ProyextoDAVWebApp.Models.NombreTrabajo", b =>
                {
                    b.HasOne("ProyextoDAVWebApp.Models.ReclutamientoTrabajo", "ReclutamientoTrabajo")
                        .WithMany()
                        .HasForeignKey("ReclutamientoTrabajoId");
                });

            modelBuilder.Entity("ProyextoDAVWebApp.Models.ReclutamientoTrabajo", b =>
                {
                    b.HasOne("ProyextoDAVWebApp.Models.Empresa", "Empresa")
                        .WithMany("ReclutamientoTrabajos")
                        .HasForeignKey("EmpresaId");
                });

            modelBuilder.Entity("ProyextoDAVWebApp.Models.Usuario", b =>
                {
                    b.HasOne("ProyextoDAVWebApp.Models.Aplicaciontrabajo", "AplicacionTrabajo")
                        .WithMany("Usuarios")
                        .HasForeignKey("AplicacionTrabajoIdUsuario")
                        .HasPrincipalKey("IdUsuario");

                    b.HasOne("ProyextoDAVWebApp.Models.EducacionUsuario", "EducacionUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("EducacionUsuarioIdUsuario")
                        .HasPrincipalKey("IdUsuario");

                    b.HasOne("ProyextoDAVWebApp.Models.OcupacionUsuario", "OcupacionUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("OcupacionUsuarioIdUsuario")
                        .HasPrincipalKey("IdUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
